# DNS Service that return A records that point to elasticsearch pods with app:elasticsearch
kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: logging
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  clusterIP: None # renders this service headless.
  ports: # these are used to interact with the RESTAPI and inter-node communication.
    - port: 9200
      name: rest
    - port: 9300
      name: inter-node