version: '3'
services: 
  frontend-lb:
    build: 
      dockerfile: 'Dockerfile'
      context: ./frontend.loadbalancer.nginx
    ports:
      - '8080:80'
  backend-api:
    build: 
      dockerfile: 'Dockerfile'
      context: ./backend.values.api
    ports:
      - '5000:80'
  frontend-web:
    build: 
      dockerfile: 'Dockerfile'
      context: ./frontend.values.web
    environment: 
      - APIURL=http://backend-api:80/
    ports:
      - '3000:80'