version: '3'
services: 
  frontend-lb:
    build: 
      dockerfile: 'Dockerfile'
      context: ./frontend.loadbalancer.nginx
    ports:
      - '8080:80'
  backend-api:
    build: 
      dockerfile: 'Dockerfile'
      context: ./backend.values.api
    ports:
      - '5000:80'