# Default values for efk-stack.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: logging

es: 
  hostName: elasticsearch
  clusterName: es-cluster
  clusterCount: 1
  clusterHosts: "es-cluster-0.elasticsearch" # separate with commas, one entry for each replica, increment for each entry. (Example: 3 cluster count becomes "es-cluster-0.elasticsearch, es-cluster-1.elasticsearch, es-cluster-2.elasticsearch" here)
  masterNodeCount: "1" # Should be = clusterCount / 2 + 1
  cpuLimit: 1000m
  cpuRequest: 100m
  javaOptions: "-Xms512m -Xmx512m"
  volumeClaimStorageClass: standard # 'standard' for Minikube, or 'default' or some other class depending on your cloud provider.
  volumeClaimSize: 5Gi
  image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.2
  imagePullPolicy: IfNotPresent

#ingress:
#  enabled: false
#  annotations: {}
#    # kubernetes.io/ingress.class: nginx
#    # kubernetes.io/tls-acme: "true"
#  hosts:
#    - host: chart-example.local
#      paths: []
#
#  tls: []
#  #  - secretName: chart-example-tls
#  #    hosts:
#  #      - chart-example.local
#
#resources: {}
#  # We usually recommend not to specify default resources and to leave this as a conscious
#  # choice for the user. This also increases chances charts run on environments with little
#  # resources, such as Minikube. If you do want to specify resources, uncomment the following
#  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
#  # limits:
#  #   cpu: 100m
#  #   memory: 128Mi
#  # requests:
#  #   cpu: 100m
#  #   memory: 128Mi
#
#nodeSelector: {}
#
#tolerations: []
#
#affinity: {}
#