apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    component: web
spec:
  containers:
  - name: web
    image: ricrob1/lab-webclient:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000